#!/usr/bin/env bash
# Setup: clear any rotated MCP log files from a previous run so post-recording
# assertions can confidently say "rotation happened during THIS session."
#
# Intentionally NOT removing the active log file — warp-oss will truncate it
# on startup anyway, and leaving it in place keeps the OS-level inode stable
# for any concurrent tail.

set -euo pipefail

MCP_LOG_DIR="${HOME}/Library/Group Containers/2BBY89MBSN.dev.warp/Library/Application Support/dev.warp.Warp-Stable/mcp"

if [[ -d "${MCP_LOG_DIR}" ]]; then
    # Remove rotated copies (`*.log.{1..N}`), rotation event sidecar, and
    # summary sidecar — anything generated by previous runs of this scenario.
    find "${MCP_LOG_DIR}" -maxdepth 1 -type f \( \
        -name '*.log.[0-9]*' \
        -o -name '*.log.rotations.jsonl' \
        -o -name '*.log.summaries.jsonl' \
    \) -print -delete | sed 's/^/cleared: /'
else
    echo "MCP log dir does not exist yet; nothing to clean."
fi
