//! README rendering for a recorded tape.
//!
//! [`render_readme`] is a pure function: it takes a fully-populated
//! [`BundleInputs`] and returns the markdown body. [`write_readme`] persists
//! that body to disk. Stages will populate `BundleInputs` once they exist
//! (P3+); for now the rendering is exercised in isolation via snapshot tests.

use std::fmt::Write as _;
use std::path::Path;

use chrono::{DateTime, Utc};

use crate::error::{Error, Result};
use crate::scenario::Scenario;

#[derive(Debug, Clone)]
pub struct BundleInputs<'a> {
    pub scenario: &'a Scenario,
    pub branch: &'a str,
    pub head: &'a str,
    pub recorded_at: DateTime<Utc>,
    pub eval_status: &'a str,
    pub artifacts: BundleArtifacts,
    pub stage_logs: Vec<StageLog>,
    pub assertion_summary: Vec<String>,
}

#[derive(Debug, Clone, Default)]
pub struct BundleArtifacts {
    pub has_master_mov: bool,
    pub patches: Vec<String>,
    pub session_log_bytes: Option<u64>,
    pub mcp_logs: Vec<String>,
}

impl BundleArtifacts {
    pub fn is_empty(&self) -> bool {
        !self.has_master_mov
            && self.patches.is_empty()
            && self.session_log_bytes.is_none()
            && self.mcp_logs.is_empty()
    }
}

#[derive(Debug, Clone)]
pub struct StageLog {
    pub name: String,
    pub tail: String,
}

impl StageLog {
    pub fn new(name: impl Into<String>, tail: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            tail: tail.into(),
        }
    }
}

pub fn render_readme(inputs: &BundleInputs) -> String {
    let mut out = String::new();

    writeln!(out, "# Tape: {}", inputs.scenario.metadata.title).unwrap();
    writeln!(out).unwrap();
    if let Some(ticket) = &inputs.scenario.metadata.ticket {
        writeln!(out, "**Ticket:** {ticket}  ").unwrap();
    }
    writeln!(
        out,
        "**Branch / head:** `{}` @ `{}`  ",
        inputs.branch, inputs.head
    )
    .unwrap();
    writeln!(
        out,
        "**Recorded:** {}  ",
        inputs.recorded_at.format("%Y-%m-%dT%H:%M:%SZ")
    )
    .unwrap();
    writeln!(out, "**Evaluation:** `{}`", inputs.eval_status).unwrap();
    writeln!(out).unwrap();

    if let Some(expected) = &inputs.scenario.metadata.expected {
        writeln!(out, "## Expected behavior").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "{expected}").unwrap();
        writeln!(out).unwrap();
    }

    if !inputs.artifacts.is_empty() {
        writeln!(out, "## Artifacts").unwrap();
        writeln!(out).unwrap();
        if inputs.artifacts.has_master_mov {
            writeln!(out, "- [master.mov](master.mov) — screen recording").unwrap();
        }
        if !inputs.artifacts.patches.is_empty() {
            writeln!(out, "- patches/ — named stills:").unwrap();
            for name in &inputs.artifacts.patches {
                writeln!(out, "    - [{name}](patches/{name})").unwrap();
            }
        }
        if let Some(bytes) = inputs.artifacts.session_log_bytes {
            writeln!(
                out,
                "- [logs/warp-oss.session.log](logs/warp-oss.session.log) — {bytes} bytes of warp-oss.log captured during the session"
            )
            .unwrap();
        }
        if !inputs.artifacts.mcp_logs.is_empty() {
            writeln!(out, "- logs/mcp/ — MCP server logs at end of session:").unwrap();
            for name in &inputs.artifacts.mcp_logs {
                writeln!(out, "    - [{name}](logs/mcp/{name})").unwrap();
            }
        }
        writeln!(out).unwrap();
    }

    if !inputs.stage_logs.is_empty() {
        writeln!(out, "## Stages").unwrap();
        writeln!(out).unwrap();
        for log in &inputs.stage_logs {
            writeln!(out, "<details><summary>{}</summary>", log.name).unwrap();
            writeln!(out).unwrap();
            writeln!(out, "```text").unwrap();
            writeln!(out, "{}", log.tail).unwrap();
            writeln!(out, "```").unwrap();
            writeln!(out, "</details>").unwrap();
            writeln!(out).unwrap();
        }
    }

    if !inputs.assertion_summary.is_empty() {
        writeln!(out, "## Assertion summary").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "```text").unwrap();
        for line in &inputs.assertion_summary {
            writeln!(out, "{line}").unwrap();
        }
        writeln!(out, "```").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "---").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "_Generated by [warp-taper](https://github.com/david-engelmann/warp-taper)._"
    )
    .unwrap();

    out
}

pub fn write_readme(out_path: &Path, inputs: &BundleInputs) -> Result<()> {
    let body = render_readme(inputs);
    std::fs::write(out_path, body).map_err(Error::Io)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn fixed_time() -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 5, 14, 4, 12, 7).unwrap()
    }

    fn minimal_scenario() -> Scenario {
        Scenario::builder("10874-mcp-log-rotation")
            .title("MCP log rotation kicks in at the size cap")
            .build()
            .unwrap()
    }

    fn full_scenario() -> Scenario {
        Scenario::builder("10874-mcp-log-rotation")
            .title("MCP log rotation kicks in at the size cap")
            .ticket("warpdotdev/warp#10874")
            .expected("An MCP server's log rotates after the size threshold is crossed.\nNo error toasts during rotation.")
            .build()
            .unwrap()
    }

    #[test]
    fn render_minimal() {
        let scenario = minimal_scenario();
        let inputs = BundleInputs {
            scenario: &scenario,
            branch: "main",
            head: "abc1234",
            recorded_at: fixed_time(),
            eval_status: "pass",
            artifacts: BundleArtifacts::default(),
            stage_logs: vec![],
            assertion_summary: vec![],
        };
        insta::assert_snapshot!("readme_minimal", render_readme(&inputs));
    }

    #[test]
    fn render_with_expected_and_artifacts() {
        let scenario = full_scenario();
        let inputs = BundleInputs {
            scenario: &scenario,
            branch: "david/advanced-log-rotation-poc",
            head: "1f41ac3a",
            recorded_at: fixed_time(),
            eval_status: "pass",
            artifacts: BundleArtifacts {
                has_master_mov: true,
                patches: vec!["01-before.png".into(), "02-after.png".into()],
                session_log_bytes: Some(48_213),
                mcp_logs: vec!["0d6c1e2a-mcp.log".into(), "0d6c1e2a-mcp.log.1".into()],
            },
            stage_logs: vec![],
            assertion_summary: vec![],
        };
        insta::assert_snapshot!("readme_with_artifacts", render_readme(&inputs));
    }

    #[test]
    fn render_full() {
        let scenario = full_scenario();
        let inputs = BundleInputs {
            scenario: &scenario,
            branch: "david/advanced-log-rotation-poc",
            head: "1f41ac3a",
            recorded_at: fixed_time(),
            eval_status: "pass",
            artifacts: BundleArtifacts {
                has_master_mov: true,
                patches: vec!["01-before.png".into()],
                session_log_bytes: Some(48_213),
                mcp_logs: vec!["0d6c1e2a-mcp.log".into()],
            },
            stage_logs: vec![
                StageLog::new("01-build.log", "warp-taper :: build\n    finished: ok"),
                StageLog::new("04-evaluate.log", "evaluate: pass"),
            ],
            assertion_summary: vec![
                "  ✓ MCP log snapshot captured (6 files)".into(),
                "  ✓ 1 rotated log file(s) present".into(),
            ],
        };
        insta::assert_snapshot!("readme_full", render_readme(&inputs));
    }

    #[test]
    fn write_readme_persists_render_output() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("README.md");
        let scenario = minimal_scenario();
        let inputs = BundleInputs {
            scenario: &scenario,
            branch: "main",
            head: "abc1234",
            recorded_at: fixed_time(),
            eval_status: "pass",
            artifacts: BundleArtifacts::default(),
            stage_logs: vec![],
            assertion_summary: vec![],
        };
        write_readme(&path, &inputs).unwrap();
        let on_disk = std::fs::read_to_string(&path).unwrap();
        assert_eq!(on_disk, render_readme(&inputs));
    }
}
